apiVersion: tekton.dev/v1
kind: Task
metadata:
  annotations:
    managed-by: Tekton
  name: operator-fetch-component-releases
spec:
  params:
  - name: components
    description: configuration file to reade
    default: components.yaml
    # TODO: Set default to nightly. Mar 09, 2022 - no nightly ("latest") releases available for Hub
  - name: TARGET_PLATFORMS
    description: Target platform for for which the payload is going to be used
    default: "kubernetes openshift"
  steps:
  - image: docker.io/library/golang:1.24
    name: fetch-components
    workingDir: /go/src/github.com/tektoncd/operator
    script: |
      #!/usr/bin/env bash
      set -e

      echo "Installing yq..."
      wget -q https://github.com/mikefarah/yq/releases/download/v4.40.5/yq_linux_amd64 -O /usr/bin/yq
      chmod +x /usr/bin/yq
      for platform in $(params.TARGET_PLATFORMS); do
        echo "Fetching Tekton components for ${platform} build"
        make TARGET=${platform} get-releases
        [[ "$?" != 0 ]] &&  exit 1
        # print directory structure of cmd/<platform>/operator/kodata
        find cmd/${platform}/operator/kodata/
      done
    securityContext:
      runAsUser: 0
  workspaces:
  - mountPath: /go/src/github.com/tektoncd/operator
    name: source
